name: monkman
favicon: null
layout_spectrum: 0.9783757880795747
typography_spectrum: 0.1349517630878836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3947891569696367
  lightness: 0.8374209164176136
  saturation: 0.7479763054288924
  rhythmicContrast: 0.13995572715066373
purpose: []
